### ISSUE TITLE
tableview上面有绘制的进度条，截图后已填充进度条颜色显示不出来

### ISSUE THREAD

**Issue by 370966584** [TonyReet/TYSnapshotScroll#11]
不知道什么原因，换了一个方法 就显示正常了
把
[self.layer renderInContext: UIGraphicsGetCurrentContext()] 
换成了
[self drawViewHierarchyInRect:self.bounds afterScreenUpdates:YES];
这两个方法有什么区别呢

**Comment by TonyReet** [comment]
@370966584 您好，谢谢您提的问题，我测试下，如果没有问题，就修改。
