### ISSUE TITLE
iPhone XS Max WKWebview 截图空白

### ISSUE THREAD

**Issue by RadioHeadach** [TonyReet/TYSnapshotScroll#13]
系统版本为 iOS 12.0.1，在您设定的美团页面截图为空白，但是在某一些页面内截图又不是空白，可复现。

**Comment by TonyReet** [comment]
> 系统版本为 iOS 12.0.1，在您设定的美团页面截图为空白，但是在某一些页面内截图又不是空白，可复现。

@RadioHeadach 谢谢，该问题已经修改，请使用最新版本验证。
