### ISSUE TITLE
你好，wkwebview截取的内容不完整，这是啥问题？

### ISSUE THREAD

**Issue by heliang219** [TonyReet/TYSnapshotScroll#14]

**Comment by TonyReet** [comment]
> _No description provided._

可以具体说下，是怎么不完整吗》

**Comment by heliang219** [comment]
就是还有些内容没有截取到啊 邮箱发张图给你看下哈

**Comment by heliang219** [comment]
发你gmail邮箱了哈

**Comment by TonyReet** [comment]
你好，我看邮件里面的照片，不是很清楚，可以加我QQ:20130639 ，具体说下吗

heliang <notifications@github.com> 于2019年2月21日周四 上午11:47写道：

**Comment by TonyReet** [comment]
已确定是异步加载问题，没有加载出来前，是截取不了的
