### ISSUE TITLE
保存的图片模糊

### ISSUE THREAD

**Issue by yangjinsong** [TonyReet/TYSnapshotScroll#15]
截取网页后保存到手机相册里面     但是打开图片看着好模糊  不清楚

**Comment by TonyReet** [comment]
> 截取网页后保存到手机相册里面 但是打开图片看着好模糊 不清楚

你好，请提供下测试的手机型号，系统版本和截取类型，谢谢。

**Comment by yangjinsong** [comment]
你好  我是在模拟器里面运行
![Simulator Screen Shot - iPhone Xʀ - 2019-05-16 at 18 19 18](https://user-images.githubusercontent.com/13938742/57846587-23aaa180-7807-11e9-9e02-d22ba78584f6.png)
的 Xcode版本是   10.2.1   模拟器是XR

**Comment by TonyReet** [comment]
> 你好 我是在模拟器里面运行的 Xcode版本是 10.2.1 模拟器是XR
> ![Simulator Screen Shot - iPhone Xʀ - 2019-05-16 at 18 19 18](https://user-images.githubusercontent.com/13938742/57846587-23aaa180-7807-11e9-9e02-d22ba78584f6.png)

你看下真机是模糊的吗，我测试下真机是没问题的
