### ISSUE TITLE
iOS13下截长图不全

### ISSUE THREAD

**Issue by 1506874981** [TonyReet/TYSnapshotScroll#16]
iOS13下截长图不全，超出屏幕部分为黑有什么解决办法或者思路吗

**Comment by TonyReet** [comment]
> iOS13下截长图不全，超出屏幕部分为黑有什么解决办法或者思路吗

您好，我这边在真机上测试了iOS13 demo里面所有情况，均没问题，你这边确认下调用TYSnapshotScroll的screenSnapshot:finishBlock:方法时，传入view是否正确，如果还有问题，请再反馈。

**Comment by 1506874981** [comment]
我用你的demo 是正常的，但是在我项目中使用 当为iOS 13时就只能截取当前屏幕

**Comment by freesan44** [comment]
我也发现类似问题了，发现是用Masonary之类的AutoLayout约束控件约束tableView/ScrollView，就会产生这个问题
