### ISSUE TITLE
iOS 13 兼容性

### ISSUE THREAD

**Issue by BerXiu** [TonyReet/TYSnapshotScroll#17]
在iOS 13 WKWebView 以下方法会失效
 CGRect myFrame = self.frame;
 myFrame.origin.y = -((index) * snapshotView.frame.size.height);
 self.frame = myFrame;

可改为 [self.scrollView setContentOffset:CGPointMake(0, index * snapshotView.frame.size.height)];

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by TonyReet** [comment]
> 在iOS 13 WKWebView 以下方法会失效
> CGRect myFrame = self.frame;
> myFrame.origin.y = -((index) * snapshotView.frame.size.height);
> self.frame = myFrame;
> 
> 可改为 [self.scrollView setContentOffset:CGPointMake(0, index * snapshotView.frame.size.height)];

您好，我在iOS13.1.2的X上测试没有问题，请问具体的场景和问题是怎样的，谢谢。

**Comment by TonyReet** [comment]
> 在iOS 13 WKWebView 以下方法会失效
> CGRect myFrame = self.frame;
> myFrame.origin.y = -((index) * snapshotView.frame.size.height);
> self.frame = myFrame;
> 
> 可改为 [self.scrollView setContentOffset:CGPointMake(0, index * snapshotView.frame.size.height)];

如果没有问题了，一周后关闭哈

**Comment by BerXiu** [comment]
我目前是改成 [self.scrollView setContentOffset:CGPointMake(0, index * snapshotView.frame.size.height)] 就没问题了。

我们这边的场景是，在ViewController 中，嵌入了一个小窗口WKWebView ，这个H5页面内容大于1页的时候。截图只会截取第一页，第二页为空白呢。WKWebView 通过约束布局。在iOS 13中，直接设置frame.origin.y 是失效的。

**Comment by TonyReet** [comment]
> 我目前是改成 [self.scrollView setContentOffset:CGPointMake(0, index * snapshotView.frame.size.height)] 就没问题了。
> 
> 我们这边的场景是，在ViewController 中，嵌入了一个小窗口WKWebView ，这个H5页面内容大于1页的时候。截图只会截取第一页，第二页为空白呢。WKWebView 通过约束布局。在iOS 13中，直接设置frame.origin.y 是失效的。

谢谢，修改下更新。
