### ISSUE TITLE
iOS 13 UIScrollView兼容性问题

### ISSUE THREAD

**Issue by gdzhujun** [TonyReet/TYSnapshotScroll#18]
在IOS13中UIScrollView截图只能显示屏幕区域的，区域外的无法显示，在iOS12中正常

**Comment by gdzhujun** [comment]
感觉比较难解决，用了几个开源库都存在同样的问题

**Comment by TonyReet** [comment]
> 感觉比较难解决，用了几个开源库都存在同样的问题

已经找到问题原因和解决方案，但是可能需要外部处理，现在在想一个比较好的框架处理方案

**Comment by TonyReet** [comment]
> 在IOS13中UIScrollView截图只能显示屏幕区域的，区域外的无法显示，在iOS12中正常

UIScrollView嵌套UITableView的问题，现需要在block里面修改对应的AutoLayout，在对应的finish里面还原layout，因为iOS13直接修改contentSize失效了，目前暂时只想到这个方案，可以参考demo。已经上传。

**Comment by TonyReet** [comment]
> 在IOS13中UIScrollView截图只能显示屏幕区域的，区域外的无法显示，在iOS12中正常

如果没有问题了，一周后关闭

**Comment by AppleTTT** [comment]
问题依然存在，iOS 13.1.3 和 iOS 13.2.2 在使用 autolayout 的 UIScrollView 上使用截屏的时候，还是会出现只能截取屏幕部分的问题

**Comment by TonyReet** [comment]
> 问题依然存在，iOS 13.1.3 和 iOS 13.2.2 在使用 autolayout 的 UIScrollView 上使用截屏的时候，还是会出现只能截取屏幕部分的问题

UIScrollView的问题，在demo里面添加了，可以参考，处理方式不同

**Comment by AppleTTT** [comment]
找到一个解决办法，截图方法里面的这句话
self.frame = CGRect(x: 0, y: 0, width: self.contentSize.width, height: self.contentSize.height)
改成这样的：
self.layer.frame = CGRect(x: 0, y: 0, width: self.contentSize.width, height: self.contentSize.height)
就可以了

**Comment by AppleTTT** [comment]
参考的这里这个：https://stackoverflow.com/questions/58517310/objective-c-scrollview-screenshot-have-a-issue-in-ios-13

**Comment by TonyReet** [comment]
> https://stackoverflow.com/questions/58517310/objective-c-scrollview-screenshot-have-a-issue-in-ios-13

已更新，谢谢提供
