### ISSUE TITLE
网页太长，内存处理问题

### ISSUE THREAD

**Issue by hydyy** [TonyReet/TYSnapshotScroll#2]
如题， 如果内容过长， 瞬间的内存会飙很高，会崩溃的吧，哥们有什么好办法？

**Comment by TonyReet** [comment]
你好，周末我会解决这个问题，谢谢提出问题

**Comment by hydyy** [comment]
@TonyReet 之前有需求要做这个， 我把长度做了限制，清晰度也调低了。勉强能用。 但是真的还是不知道怎么解决内存问题， 哥们说说思路？

**Comment by TonyReet** [comment]
@hydyy 恩，确实。如果网页很长，图片就会多，内存就会上升，我也没有想出什么办法😂。之前我想的是保存成文件再拼接图片，但是图片多了后再拼接还是有这样的问题。使用https://worlds-highest-website.com 测试的，感觉无解。求大神😂

**Comment by hydyy** [comment]
哎 我也是各种尝试啊， 还是不行，不敢用高清的上线， 图片稍多就崩。高端的机器还好，低端手机那真实没法玩

**Comment by TonyReet** [comment]
@hydyy 您的网页有多长，可以发来看下吗？

**Comment by hydyy** [comment]
很长，用户自己编辑的内容。 不可预期的。

**Comment by Barry-Wang** [comment]
ios9 WkWebView 无法生成图片

**Comment by TonyReet** [comment]
@Barry-Wang 你好，已经处理了WKWebView的截图问题，年底了，公司比较忙，可能不能及时处理

**Comment by WildDylan** [comment]
关于内存的问题，有个小的思路，不要直接做成一张图。 很长的网页，我们可以比作好多图，然后做一个flush缓冲队列，然后在收到内存警告或者超过缓冲队列长度或者总size的时候马上写入到本地。

**Comment by TonyReet** [comment]
@WildDylan 谢谢大神指点， 这样可以试试

**Comment by hydyy** [comment]
@WildDylan  但是避免不了最后的合成呀，多张小图终究是要拿出来拼合成一张图的

**Comment by luoxiao** [comment]
忍不住说两句，无意间搜内存问题，看到这，刚下载demo看了下，其实这个截图方案太复杂了，再者用demo 的webview截图百度主页，你会发现底部错乱，还有截图没显示的问题。

我在高德地图路线上做的截图比较简单，内存消耗相对较少。
后来自己又做了些优化，上线了个截图app  https://itunes.apple.com/app/id1122924652?mt=8

受限于苹果内存限制有时也会crash，也在想办法，我觉得还有提高的地方。

**Comment by TonyReet** [comment]
@luoxiao 嗯嗯，内存限制的问题，现在没有想到办法。所有的图片都要进行拼接，如果太多肯定就超过了内存限制，如果有好的思路请告知下，谢谢
