### ISSUE TITLE
WKWebView截长图拼接有的时候会不正常

### ISSUE THREAD

**Issue by ifshyse** [TonyReet/TYSnapshotScroll#20]
有的时候会把第一张图一部分拼到后面

**Comment by ifshyse** [comment]
是在iPhone 11 pro max上出现的

**Comment by TonyReet** [comment]
> 有的时候会把第一张图一部分拼到后面
您好，请问有规律吗，我这边只有x和xs max  看了没问题，请问下具体复现情况
