### ISSUE TITLE
用storyBoard或xib画的tableview在iOS13下还是有问题

### ISSUE THREAD

**Issue by DyingPeter** [TonyReet/TYSnapshotScroll#23]
1.截图的时候会跳一下
2.截图不稳定,有时候会有空白区域,有时候会少截一部分

**Comment by TonyReet** [comment]
> 1.截图的时候会跳一下
> 2.截图不稳定,有时候会有空白区域,有时候会少截一部分

你好，demo里面的『SB_ScrollView嵌套TableView_截图』是StoryBoard的ScrollView嵌套TableView，这个demo你那边会有问题吗？

**Comment by DyingPeter** [comment]
demo里没有问题,但是不知道我这情况是怎么回事...

**Comment by TonyReet** [comment]
> demo里没有问题,但是不知道我这情况是怎么回事...

如果方便的话，你可以把你有问题的代码脱敏后发到邮箱ktonyreet@gmail.com
