### ISSUE TITLE
WKWebView如果加载的是PDF文件的话，截取到的是灰色的图片

### ISSUE THREAD

**Issue by CoderWeiLee** [TonyReet/TYSnapshotScroll#26]

**Comment by CoderWeiLee** [comment]
有什么比较好的解决办法吗

**Comment by TonyReet** [comment]
> 有什么比较好的解决办法吗

推测是pdf内容没有显示就开始截图了，你可以使用:        
[TYSnapshotScroll screenSnapshot:self.snapView addMaskAfterBlock:nil finishBlock:^(UIImage *snapshotImage) {
            // do something
        }];

看截图时是否显示完成，如果没有显示完成， 可以试着配置下每次截图时间，使用单例[TYSnapshotManager defaultManager]的delayTime配置。

**Comment by CoderWeiLee** [comment]
已经看到页面完全加载出来了，多次尝试都是这样的。而且，经过一番搜索，似乎都有这样的问题。StackoverFlow上

**Comment by TonyReet** [comment]
添加了pdf截图，目前是先下载PDF再转成图片，方案不是很完美

**Comment by TonyReet** [comment]
添加了PDF截图及DEMO，目前是先下载PDF再转成图片，方案不是很完美
