### ISSUE TITLE
UITextView 也想截图

### ISSUE THREAD

**Issue by Jayxiang** [TonyReet/TYSnapshotScroll#27]
为何没有直接判断 [snapshotView isKindOfClass:[UIScrollView class]]
我现在 UITextView 也需要截图，看看能加上吗。
我试着加上发现文字截不全。

**Comment by Jayxiang** [comment]
找到问题了，是iOS 13的问题。[iOS 13 UITextView converting UITextView to image is not working properly. Working fine in below iOS 12
](https://stackoverflow.com/questions/58405106/ios-13-uitextview-converting-uitextview-to-image-is-not-working-properly-workin)

**Comment by TonyReet** [comment]
> 找到问题了，是iOS 13的问题。[iOS 13 UITextView converting UITextView to image is not working properly. Working fine in below iOS 12 ](https://stackoverflow.com/questions/58405106/ios-13-uitextview-converting-uitextview-to-image-is-not-working-properly-workin)

谢谢提供，demo和pod已经更新

**Comment by Jayxiang** [comment]
1.demo 无法 pod
2.是 UITextView，不是 UITextField
3.新的还是没有判断 UITextView
4.用上面方式解决后还有一个问题，就是截图后 UITextView 不能滑动了，必须输入内容后才能滑动。

**Comment by TonyReet** [comment]
> 1.demo 无法 pod
> 2.是 UITextView，不是 UITextField
> 3.新的还是没有判断 UITextView
> 4.用上面方式解决后还有一个问题，就是截图后 UITextView 不能滑动了，必须输入内容后才能滑动。

1、我clone一份demo，可以pod
2、3已经修改
4、demo在13.4.1的iPhoneX，13.4的6s，10.3的6测试，截图后正常，能够正查岗你滑动。

**Comment by Jayxiang** [comment]
Analyzing dependencies
[!] No podspec found for `TYSnapshotScroll` in `../TYSnapshotScroll`

demo pod 还是报错

**Comment by TonyReet** [comment]
可以了

**Comment by Jayxiang** [comment]
如果是直接下载 demo，然后 pod，还是有一些报错。简单修改一下就可以了。你可以试试。
