### ISSUE TITLE
不支持bitcode

### ISSUE THREAD

**Issue by 275080225** [TonyReet/TYSnapshotScroll#29]
TYSnapshotAuxiliary.framework可否开源,或支持bitcode

bitcode bundle could not be generated because 'xxxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary(UIScrollView+TYSnapshotAuxiliary.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file 'xxxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary' for architecture arm64

**Comment by TonyReet** [comment]
> TYSnapshotAuxiliary.framework可否开源,或支持bitcode
> 
> bitcode bundle could not be generated because 'xxxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary(UIScrollView+TYSnapshotAuxiliary.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file 'xxxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary' for architecture arm64

已修改，请看下是否还有问题

**Comment by 275080225** [comment]
已解决
