### ISSUE TITLE
不支持bitcode吗 希望能支持

### ISSUE THREAD

**Issue by huangxianyu** [TonyReet/TYSnapshotScroll#30]
ld: bitcode bundle could not be generated because '/Users/ycx/Desktop/YCX-iOS/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary(UIScrollView+TYSnapshotAuxiliary.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/ycx/Desktop/YCX-iOS/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TonyReet** [comment]
已经修改，请查看是否还有问题
