### ISSUE TITLE
tableview截图请问有办法将navigationbar也截上么？

### ISSUE THREAD

**Issue by GLW-Eric** [TonyReet/TYSnapshotScroll#35]
你好，我有个需求是截取tableView的长图内容后，还需要截图中有导航栏的内容，请问有办法实现么？谢谢大神

**Comment by CoderWeiLee** [comment]
估计要自己拼接的

**Comment by TonyReet** [comment]
> 你好，我有个需求是截取tableView的长图内容后，还需要截图中有导航栏的内容，请问有办法实现么？谢谢大神

这个需求可以使用UIView截取navigationbar，然后自己拼接下
