### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Catlc** [TonyReet/TYSnapshotScroll#36]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebView screenSnapshotNeedMask:addMaskAfterBlock:finishBlock:]: unrecognized selector sent to instance 0x7f94ea858a00'

**Comment by TonyReet** [comment]
> screenSnapshotNeedMask:addMaskAfterBlock:finishBlock

您好，请问下，导入"WKWebView+TYSnapshot"这个类了吗
