### ISSUE TITLE
不支持bitcode

### ISSUE THREAD

**Issue by charleslinkn** [TonyReet/TYSnapshotScroll#37]
bitcode bundle could not be generated because '/xxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary(UIScrollView+TYSnapshotAuxiliary.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/xxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary' for architecture armv7

**Comment by TonyReet** [comment]
> bitcode bundle could not be generated because '/xxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary(UIScrollView+TYSnapshotAuxiliary.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/xxx/Pods/TYSnapshotScroll/TYSnapshotScroll/TYSnapshotAuxiliary.framework/TYSnapshotAuxiliary' for architecture armv7

请参考issue[#29 ](https://github.com/TonyReet/TYSnapshotScroll/issues/29)，此问题已经修改了，确定是否是最新的
