### ISSUE TITLE
IOS11 下 UIScrollView 不可见部分无法截图

### ISSUE THREAD

**Issue by 419620942** [TonyReet/TYSnapshotScroll#4]
WebView等可以完美的截图，UIScrollView的不可见部分无法截图？作者有注意到这个问题吗？

**Comment by TonyReet** [comment]
@419620942 你好，我这边验证下，是可以
![1](https://user-images.githubusercontent.com/18474785/33121524-fc0a39e8-cfaf-11e7-8b1b-7c06936ecaa5.png)
![2](https://user-images.githubusercontent.com/18474785/33121525-fc3b6eaa-cfaf-11e7-8695-ccd4197f7ca1.png)

的
