### ISSUE TITLE
TYSnapshotAuxiliary.framework 不支持模拟器

### ISSUE THREAD

**Issue by 460467069** [TonyReet/TYSnapshotScroll#40]
TYSnapshotAuxiliary.framework 不支持模拟器

**Comment by 460467069** [comment]
Architectures in the fat file: TYSnapshotAuxiliary are: armv7 arm64

**Comment by jackliuheh** [comment]
解决办法：File -》 Workspace Settings -》 Build System改成Legacy Build System
