### ISSUE TITLE
WKWebview长截图没有效果

### ISSUE THREAD

**Issue by zhoupIT** [TonyReet/TYSnapshotScroll#42]
我使用的是demo，因为长截图的那个地址 *https://worlds-highest-website.com/zh/* 貌似失效了，我换了一个地址 
 *http://www.eastlnk.com:8237/#/pages/instructions/instructions* ，然后发现只能截当前屏幕，不能截长图。
1. 修改的地方：TYWKWebViewVc类  url地址
2. 其它信息：
    - 库的版本是0.3.3
    - Xcode12.1  
    - 模拟器iPhone 12 Pro Max - 14.1

**Comment by TonyReet** [comment]
已修复
