### ISSUE TITLE
支持 UICollectionView 吗

### ISSUE THREAD

**Issue by LiberalChen** [TonyReet/TYSnapshotScroll#5]
支持 UICollectionView 吗

**Comment by TonyReet** [comment]
@LiberalChen 周末看哈，工作日忙项目的事情

**Comment by TonyReet** [comment]
@LiberalChen 您看下，已经修改

**Comment by LiberalChen** [comment]
@TonyReet 好的 谢谢啦

**Comment by LiberalChen** [comment]
![wechatimg248](https://user-images.githubusercontent.com/19303164/34346353-aaaac166-ea31-11e7-9293-4feb8e680cce.jpeg)
有个问题~出来的图片，只有当前屏幕的内容，能显示出来

**Comment by LiberalChen** [comment]
下面的数据 出不来呀

**Comment by TonyReet** [comment]
@LiberalChen 您好，可以提供下demo吗，我复现下，邮箱20130639@qq.com 谢谢

**Comment by LiberalChen** [comment]
@TonyReet 稍等哈

**Comment by LiberalChen** [comment]
@TonyReet 发过去了

**Comment by crazypoo** [comment]
collection不能使用哦
