### ISSUE TITLE
超长图片的内存问题

### ISSUE THREAD

**Issue by Alphts** [TonyReet/TYSnapshotScroll#6]
如果需要保存的webview或者scrollview长度很大，达到上万个点，直接上下文绘制内存会炸，有没有好的思路在这种情况下生成长图

**Comment by TonyReet** [comment]
@Alphts 你好，是这样的，之前看过这个问题。因为流程大概是先截图，然后拼接，当图片数量很大的时候，内存肯定会增加，目前想到的只能是达到一定数量分段保存。

**Comment by Alphts** [comment]
感谢回答，我之前也是用这个思路去做的，比直接截图内存上优化了很多，但是拼接的时候还是有内存问题，这类问题放在客户端实现本身就容易达到内存瓶颈。

**Comment by GitWangKai** [comment]
搞了半天没找到解决办法😢

**Comment by TonyReet** [comment]
目前修改为分段截图，x实测可以截取100个屏长度的图，使用单例[TYSnapshotManager defaultManager]的maxScreenCount配置。
