### ISSUE TITLE
WKWebView 长截图问题

### ISSUE THREAD

**Issue by HuangWeiDongiOS** [TonyReet/TYSnapshotScroll#8]
WKWebView长截图时，如果WKWebView控件不是占满整个父控件的视图，比如如说底部有个按钮（产品设计的。。。你懂得）。添加的遮盖是不能完全遮住视图的呢。会看到截图的抖动过程

**Comment by Turnarounds** [comment]
哥们你有解决这个问题吗?

**Comment by TonyReet** [comment]
> WKWebView长截图时，如果WKWebView控件不是占满整个父控件的视图，比如如说底部有个按钮（产品设计的。。。你懂得）。添加的遮盖是不能完全遮住视图的呢。会看到截图的抖动过程

不好意思，很久没上来看了，该问题已经修改好了，如果还需要的话，请更新。
